---

- hosts: app_server
  vars:
    home: /home/ansible
  #become: yes
  #become_user: ubuntu
  #become_method: sudo
  tasks:

  - name: debug variable
    debug: var=home

  - name: creating file
    file:
      path: "{{ home }}/test-ansible"
      state: touch
    register: task1

  - name: debugging task output
    debug: var=task1
    
  - name: Log into DockerHub
    docker_login:
      username: docker
      password: rekcod
    
  - name: remove container
    docker_container:
      name: tomcatwebapp
      state: absent
    
  - name: pull image from docker hub
    docker_image:
      name: siddeshg672/testdockerpush:july_{{ BUILD_NUMBER }}
      
  - name: Re-create a redis container
    docker_container:
      name: tomcatwebapp
      image: siddeshg672/testdockerpush:july_{{ BUILD_NUMBER }}
      state: present
      exposed_ports:
        - 6379
